name: wellnessz_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  lottie: ^2.3.0
  firebase_core: ^2.8.0
  firebase_analytics: ^10.5.1
  google_sign_in: ^6.2.1
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  shimmer: ^2.0.0
  cached_network_image: ^3.3.0
  share_plus: ^6.3.2
  flutter_local_notifications: ^13.0.0
  get: ^4.6.5
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.6.9
  dynamicutils: ^1.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2
  photo_manager: ^3.0.0-dev.2
  flutter_image_compress: ^2.0.4
  image_cropper: ^5.0.0
  firebase_in_app_messaging: ^0.7.3+7
  url_launcher: ^6.1.14
  http: ^1.1.2
  device_preview: ^1.1.0
  firebase_crashlytics: ^3.4.8
  animate_do:
  introduction_screen: ^3.1.12
  otp_text_field: ^1.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/PNG/
    - assets/SVG/
    - assets/Lottie/


  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/popins.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/lato.ttf
